### ISSUE TITLE
V1.8.5 of Microsoft-Win32-Content-Prep-Tool bad :(

### ISSUE THREAD

**Issue by BryceAtSabre** [NicklasAhlberg/RockMyPrinters#5]
Hi,
RockMyPrinters seems to use IntuneWinAppUtil.exe located in %userprofile%/Appdata/Local/Temp/ folder.
V1.8.5 of Microsoft-Win32-Content-Prep-Tool seems to be having issues. Just an FYI, I had to replace that executable with a previous version like V1.8.4 to get this working.

**Comment by NicklasAhlberg** [comment]
Thanks for reaching out!

//Nicklas
