### ISSUE TITLE
Enterprise Application Error

### ISSUE THREAD

**Issue by solarsystemsit** [NicklasAhlberg/RockMyPrinters#6]
Hello,

Currently getting the error: "Application with identifier 'd1ddf0e4-d672-4dae-b554-9d5bdfd93547' was not found in the directory"

After doing a little digging I've discovered [this](https://www.reddit.com/r/Intune/comments/1bfmqd7/plan_for_change_update_your_powershell_scripts/) that is more than likely causing the issue.

**Comment by CloudCaptn** [comment]
getting the same error, think we have to create an own app and use this. Is it possible to customize this? 

More infos: https://learn.microsoft.com/en-us/samples/microsoftgraph/powershell-intune-samples/important/

**Comment by NicklasAhlberg** [comment]
Hi, I am working on a solution. Hope to have a new version ready soon.

**Comment by colofdurty** [comment]
The intune Powershell api was removed. Maybe insted of it you could run the graph api

**Comment by NicklasAhlberg** [comment]
Version 1.0.2.1 is now available. Check it out!
